apiVersion: v1
kind: Service
metadata:
  name: {{ include "azure-voting-app.fullname" . }}-frontend
  labels:
    app.kubernetes.io/name: {{ include "azure-voting-app.name" . }}
    helm.sh/chart: {{ include "azure-voting-app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "azure-voting-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
